apiVersion: v1
kind: Service
metadata:
  name: civicpulse-frontend
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "civicpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "civicpulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
