apiVersion: v1
kind: Service
metadata:
  name: civicpulse-mongodb
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "civicpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
      name: mongodb
  selector:
    {{- include "civicpulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
