{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.existingSecret | default (printf "%s-secret" (include "civicpulse.fullname" .)) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "civicpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_ACCESS_SECRET: {{ .Values.secret.jwtAccessSecret | default "" | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secret.jwtRefreshSecret | default "" | quote }}
  DEFAULT_PASSWORD: {{ .Values.secret.defaultPassword | default "" | quote }}
{{- end -}}
