apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: civicpulse
  namespace: argocd
  labels:
    app.kubernetes.io/name: civicpulse
    app.kubernetes.io/part-of: civicpulse-ai
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tharunadhithyaa/intelligent-self-healing-cicd.git
    targetRevision: main
    path: helm/civicpulse
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: civicpulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
