import { Pipe, PipeTransform } from '@angular/core';
import { marked } from 'marked';
import DOMPurify from 'dompurify';

@Pipe({
  name: 'markdown',
  standalone: true,
})
export class MarkdownPipe implements PipeTransform {
  transform(value: string | undefined): string {
    if (!value) return '';

    // Parse markdown to HTML
    const rawHtml = marked.parse(value) as string;

    // Sanitize raw HTML generated by marked using DOMPurify with a strict allowlist.
    // DOMPurify removes malicious scripts, event handlers, dangerous URL schemes, and XSS vectors.
    // Returning a sanitized HTML string allows Angular's innerHTML binding to safely render it
    // without bypassing Angular's security mechanism.
    return DOMPurify.sanitize(rawHtml, {
      ALLOWED_TAGS: [
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'p',
        'br',
        'hr',
        'span',
        'div',
        'code',
        'pre',
        'blockquote',
        'ul',
        'ol',
        'li',
        'table',
        'thead',
        'tbody',
        'tr',
        'th',
        'td',
        'a',
        'img',
        'strong',
        'em',
        'del',
        'ins',
        'sub',
        'sup',
      ],
      ALLOWED_ATTR: ['href', 'title', 'target', 'rel', 'src', 'alt', 'class'],
      FORBID_TAGS: ['script', 'iframe', 'object', 'embed', 'form', 'style', 'input'],
      FORBID_ATTR: [
        'onerror',
        'onload',
        'onclick',
        'onmouseover',
        'onmouseout',
        'onkeydown',
        'onkeypress',
        'onkeyup',
      ],
      ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|ftp|tel):|[^:]+$|\/|\.\/|#)/i,
    });
  }
}
